### PR TITLE
Local monaco editor

### LINKED ISSUE #109: UI Dashboard can't work offline
The UI Dashboard loads the monaco-editor package from an online CDN.
So the Dashboard console can't work while offline or on Kubernetes Pods without internet access

## Current Behavior

Console won't load

## Steps to Reproduce

1. Try to use the dashboard console on an offline machine

## Expected Behavior

Loading the dependencies from the UI server.

## Possible Solution

Add monaco-editor as a local dependency

### PR DESCRIPTION
**Pull request by trean**
By default, the `monaco-react` package utilizes CDN to download the Monaco Editor files. This PR adds a loader as advised in the package docs to be able to use an editor locally without internet access.

Resolves #109

### CODE REVIEW

**Comment by kartik-gupta-ij** [comment]
@trean, the autocomplete feature is not working as expected.

**Review by kartik-gupta-ij — COMMENTED** [review]
Those icons are not loading properly!

Screenshot 2023-11-11 at 3 44 17 PM

**Comment by trean** [comment]
> Those icons are not loading properly!
> Screenshot 2023-11-11 at 3 44 17 PM

@kartik-gupta-ij Can not reproduce. Could you please give steps to reproduce this problem?

**Comment by trean** [comment]
> @trean, the autocomplete feature is not working as expected.

Thanks for the check, fixed.

**Comment by kartik-gupta-ij** [comment]
> > Those icons are not loading properly!
> > Screenshot 2023-11-11 at 3 44 17 PM
> 
> @kartik-gupta-ij Can not reproduce. Could you please give steps to reproduce this problem?

It's fixed, there was some issue with the node module

**Review by kartik-gupta-ij — APPROVED** [review]

**Pull request merged**
