### PR TITLE
Find similar by ID or filter by payload key:value pair.

### PR DESCRIPTION
**Pull request by kartik-gupta-ij**
https://github.com/qdrant/qdrant-web-ui/assets/84975264/3fb40ca5-850e-485a-ab54-c0fdd63fa5b8

### CODE REVIEW

**Comment by trean** [comment]
Screenshot 2024-03-12 at 13 49 03


@kartik-gupta-ij could be useful to restrict users from applying the same filter multiple times. WDYT?

Also would be nice to make it clearer that the user can click on payload values (`cursor: pointer`)

**Comment by trean** [comment]
> Screenshot 2024-03-12 at 13 49 03
> 
> @kartik-gupta-ij could be useful to restrict users from applying the same filter multiple times. WDYT?
> 
> Also would be nice to make it clearer that the user can click on payload values (`cursor: pointer`)

Alternatively: adding a filter button to each payload value could be more convenient, it lets us make URLs in the payload clickable, etc

**Comment by kartik-gupta-ij** [comment]
> > Screenshot 2024-03-12 at 13 49 03
> > @kartik-gupta-ij could be useful to restrict users from applying the same filter multiple times. WDYT?
> > Also would be nice to make it clearer that the user can click on payload values (`cursor: pointer`)
> 
> Alternatively: adding a filter button to each payload value could be more convenient, it lets us make URLs in the payload clickable, etc

Screenshot 2024-03-12 at 8 31 18 PM

@trean fixed!

**Comment by generall** [comment]
If I try to click `filter` button on the values like `12.5` (float point) it fails with error. I propose to only propose filters for string fields and integers (ideally, only for indexed fields, as in large collection filtering by non-indexed fields can be very expensive)


Also, button to clear the search string doesn't seem to work:

image

**Review by generall — APPROVED** [review]

**Pull request merged**
