### PR TITLE
Changed the default React Logo with Qdrant's Logo of appropriate dimensions.

### PR DESCRIPTION
**Pull request by Programmer-Dost**
The files 'logo192' and 'logo512', containing the React Logo, were replaced with Qdrant's logo, maintaining the same file name and required dimensions.

### CODE REVIEW

**Review by timvisee — CHANGES_REQUESTED** [review]
Thank you for putting effort into this.

I do see two problems though:
1. First of all, the new images seem to be in quite low resolution.
2. The proportions of the logo in the new images are not kept intact. Here you see it overlayed on the Qdrant logo from the front page, note the selection outline: 
image

**Comment by Programmer-Dost** [comment]
Can you please provide me the original Qdrant logo? I'd had to crop the Qdrant logo because I can't find it anywhere on the internet.

**Comment by timvisee** [comment]
> I needed to unlock the aspect ratio for converting it to 192x192 dimensions.

This should be kept locked. The rest can be filled with whitespace.

We have icons in the correct sizes that are currently used on Chrome/Android. It is probably best to use those:
- https://github.com/qdrant/landing_page/blob/master/qdrant-landing/themes/qdrant/static/images/android-chrome-512x512.png
- https://github.com/qdrant/landing_page/blob/master/qdrant-landing/themes/qdrant/static/images/android-chrome-192x192.png

**Comment by Programmer-Dost** [comment]
Please can you re-check this pull request

**Comment by timvisee** [comment]
That looks a lot better. Thank you!

image

**Review by timvisee — APPROVED** [review]

**Review by kartik-gupta-ij — APPROVED** [review]
Looks Good to me

**Review by generall — APPROVED** [review]

**Pull request merged**
