### PR TITLE
Add Settings UI

### PR DESCRIPTION
**Pull request by thekillingspree**
- Created a New Page for Settings, with a Context to pass down the settings. 
- Currently, the settings support two fields, Custom Endpoint URL and API Key.
- This is useful to query Qdrant instances running on Qdrant Cloud Platform or other cloud services.

image

### CODE REVIEW

**Comment by kartik-gupta-ij** [comment]
@thekillingspree This is not working as expected.

image
image
image

**Comment by thekillingspree** [comment]
Hi @kartik-gupta-ij, looks like this is being caused due to a CORS issue. 

Screenshot 2023-04-20 at 12 50 25 AM


I had originally tested this with my own instance deployed on Azure Cloud, where I had control over the CORS and had enabled it for testing this feature. 

image


image

Checking the original Qdrant code, we can see that CORS is enabled by default in the configuration. 

image

Not sure why the instances deployed to AWS are not accepting CORS request

**Comment by generall** [comment]
@thekillingspree will looks into CORS problem and merge your PR after that, if it works for you

**Comment by thekillingspree** [comment]
> @thekillingspree will looks into CORS problem and merge your PR after that, if it works for you

Works, definitely!

**Comment by generall** [comment]
Web UI is now part of the qdrant, this should cover the issue

**Pull request closed without merging**
