### PR TITLE
Move from CRA/JS to Vite/TS

### PR DESCRIPTION
**Pull request by CarlosZiegler**
# Pull Request Description

## Related issues
https://github.com/qdrant/qdrant-web-ui/issues/16
https://github.com/qdrant/qdrant-web-ui/issues/37
https://github.com/qdrant/qdrant-web-ui/pull/35

## Description

This pull request implements several improvements to the existing CRA App by moving it to either Vite or Next with TypeScript. In addition, it utilizes React Query for data fetching and Zod for some validations.

To enhance code organization and maintainability, the codebase has been restructured into different layers, including API, Hooks, Config, Routes, Schema, Services, and Utils. These layers have been added to improve code modularity and separation of concerns.

The implementation also includes the addition of keybinds to trigger queries, making the user experience more seamless and intuitive. To improve testing, Jest has been replaced with Vitest.

However, further refinement is required in the following areas:

### Components
The current implementation lacks proper componentization, and this pull request aims to address this by creating reusable, independent components. This will improve code organization and maintenance, as well as enhance the overall scalability of the application.

### Types
This pull request currently lacks sufficient types, and we need to implement proper type annotations throughout the codebase. This will improve code readability and catch potential errors before runtime.

### Editor Hooks for Data Fetching
To improve the user experience, we want to create hooks that allow users to fetch data directly from the editor. This will enable more seamless data retrieval and make the application more user-friendly.

Overall, this pull request will improve the maintainability, scalability, and user experience of the CRA App by moving it to Vite or Next with TypeScript, utilizing React Query and Zod, restructuring the codebase into different layers, adding keybinds, and changing the testing framework to Vitest.

### Deploy

Deployment on Vercel and Demo
This pull request includes deployment to Vercel, a cloud platform for static and serverless deployment. Vercel provides seamless integration with Git and automatic deployments, making it an excellent choice for our project.

The demo for this project is available online at [https://qdrant-web-ui-demo.vercel.app/](https://qdrant-web-ui-demo.vercel.app/). Users can access the demo and interact with the application to test its features and functionalities.

### CODE REVIEW

**Comment by generall** [comment]
Hi @CarlosZiegler that is great effort!

Do you think it might be possible to introduce changes gradually? Of not, I will just merge it as-is without a review.

**Comment by generall** [comment]
Here is some top-level feedback:
- It looks like the commands to run server are updated. Would be nice to reflect it in README
- Qdrant favicon is lost
- It feels like vite is really faster, I like that

@CarlosZiegler it would really help if you could split this PR into multiple smaller once, otherwise it is quite hard to synchronize with all the changes we already have in conflict.

I would start with Vite and then I would gradually integrate TS in the codebase.

**Comment by generall** [comment]
@CarlosZiegler I can't resolve conflicts, as I don't have access to your branch. You would need to do it from your side.

**Comment by CarlosZiegler** [comment]
> @CarlosZiegler I can't resolve conflicts, as I don't have access to your branch. You would need to do it from your side.

This was to changes that I was integrated before open PR. Now it will work.

**Comment by generall** [comment]
https://github.com/qdrant/qdrant-web-ui/issues/39

**Pull request closed without merging**
