### PR TITLE
Add "Commands" tooltip on hover to the list commands Button in Console View

### LINKED ISSUE #138: Add "Commands" tooltip to the list commands icon
image

It's not clear what the icon does, it can be misrepresented as a "RUN all commands" or "Open new console" etc.

Adding a tooltip on hover that says "Commands" or something similar will make it clearer to the user.

If this issue is entertained, I would like to work on this.

### PR DESCRIPTION
**Pull request by Snehil-Shah**
Fixes #138

image

### CODE REVIEW

**Review by trean — COMMENTED** [review]
Looks good, thank you! Could you please run `npm run format` and then commit changes so that we could merge this PR?

**Review by Snehil-Shah — COMMENTED** [review]
> Looks good, thank you! Could you please run `npm run format` and then commit changes so that we could merge this PR? 

Done

**Review by trean — APPROVED** [review]
Thank you so much!

**Comment by Snehil-Shah** [comment]
@kartik-gupta-ij Ran `npm audit fix` to fix the failing workflow, can you run it again?

**Pull request merged**
