### PR TITLE
Page for generating JWT

### PR DESCRIPTION
**Pull request by trean**

### CODE REVIEW

**Comment by generall** [comment]
To debug, service needs to be started with `-e QDRANT__SERVICE__JWT_RBAC=true -e QDRANT__SERVICE__API_KEY=qdrant`

**Comment by generall** [comment]
> can the addition of collection rules be triggered with a ➕ in the Collections pane

How to specify collection name in this case? As a selector inside dialog?

**Comment by coszio** [comment]
> As a selector inside dialog?

Yes!

**Comment by generall** [comment]
done

**Review by generall — APPROVED** [review]

**Pull request merged**
