### PR TITLE
add collections page

### PR DESCRIPTION
**Pull request by DragnEmperor**
Addresses issue #2.
The page uses simple sorting function which sorts alphabetically and groups them on basis of first letter.

Screenshot (1554)

Also encountered the following bug while switching between pages:
Screenshot (1555)

This occurred due to 'theme' property of editor window, commenting which removed the bug.

### CODE REVIEW

**Comment by kartik-gupta-ij** [comment]
>Also encountered the following bug while switching between pages:

>This occurred due to 'theme' property of editor window, commenting which removed the bug.

That is already fixed you 
It will automatically be reflected as the history PR Merges... #12

**Comment by generall** [comment]
Hi @DragnEmperor, please consider using standard components from MUI.

If you need reference, please consider finding relevant components in the examples here:

https://mui.com/store/#populars

There is a bunch of free templates which might contain re-usable components.

**Comment by kartik-gupta-ij** [comment]
> Also encountered the following bug while switching between pages: Screenshot (1555)
> 
> This occurred due to 'theme' property of editor window, commenting which removed the bug

@DragnEmperor  Please sync your branch as the issue is resolved.

**Comment by DragnEmperor** [comment]
> 
> @DragnEmperor Please sync your branch as the issue is resolved.

Alright. Thanks!

**Comment by DragnEmperor** [comment]
> Hi @DragnEmperor, please consider using standard components from MUI.
> 
> If you need reference, please consider finding relevant components in the examples here:
> 
> https://mui.com/store/#populars
> 
> There is a bunch of free templates which might contain re-usable components.

Okay. Working on it.

**Comment by DragnEmperor** [comment]
Hey @generall 
I have redesigned the collections view as per your suggestion.
I am now using Table from MUI to list the collections as in the image:
Screenshot (1557)


I was thinking of displaying info about the particular collection on right hand side of the collections table to fill the unused space. What do you think?
Is this fine?

**Comment by DragnEmperor** [comment]
Hey @generall ,
I have redesigned the collections Page using Data Grid, and viewing single collection in the Editor on right side of collections table as shown in the images in the link below:
https://imgur.com/a/HCXCm6U

Also the particular collection's page can be visited via 'More' btn.


Please review. Thanks!!!

**Comment by generall** [comment]
closed in favor of https://github.com/qdrant/qdrant-web-ui/pull/26

**Pull request closed without merging**
