### PR TITLE
Command list

### PR DESCRIPTION
**Pull request by trean**
Screenshot 2023-11-09 at 01 43 59

### CODE REVIEW

**Comment by timvisee** [comment]
Very nice! :smile:

**Comment by generall** [comment]
Let's only react on click on arrow button, not the whole panel.

**Comment by generall** [comment]
Optimize list scrolling in case of holding arrow keys

**Comment by generall** [comment]
let's replace fuzzy search with some proper keyword/prefix matching

**Review by generall — APPROVED** [review]

**Pull request merged**
